apiVersion: v1
kind: Service
metadata:
  name: werwertrain-service
spec:
  selector:
    app: werwertrain
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 30008
  type: NodePort
